### ISSUE TITLE
How long does it take

### ISSUE THREAD

**Issue by miganchuanbo** [ankanbhunia/PIDM#11]
Hi, Very interesting and nice results.
I am wondering how long does it take to train the model.

**Comment by ankanbhunia** [comment]
5 days with 8 A100 GPUs on deepfashion dataset.

**Comment by miganchuanbo** [comment]
Thanks!

**Comment by fiona-lxd** [comment]
> 5 days with 8 A100 GPUs on deepfashion dataset.

Hi, I have reproduced the experiments with the default setting except for the batch size which is set to 16 instead of  on 8 A100 GPUs. However, it takes about 950 seconds for one epoch. According to the default setting where the total epochs is 1000, it will take about 10-11 days on DeepFashion dataset instead of the mentioned 5 days. Is there any thing I did wrong? Can you help me figure it out?

**Comment by fiona-lxd** [comment]
Got it. Thank you very much for the quick reply.
