### ISSUE TITLE
The result of running the model is not so perfect

### ISSUE THREAD

**Issue by BOSSJCH** [ankanbhunia/PIDM#31]
![6b0cfa36aaa3e89626200041af4146a](https://github.com/ankanbhunia/PIDM/assets/93815925/61810a48-d5cc-442a-a34c-b408f9649784)
When I used the checkpoints you provided and the demo on the web page to generate pictures, the results didn't seem so good. Especially the facial features of characters.
Is there anything wrong with my operation?
@ankanbhunia

**Comment by ankanbhunia** [comment]
It appears that the issue is not in the model itself, but rather in how we are evaluating it in the demo. The target poses used in the input do not belong to the subject in the source image, but are instead randomly chosen from a set of predefined poses. You can imagine that a different target pose (which doesn't belong to the subject) can induce inconsistent facial/body structures (due to dissimilar facial/body keypoints), resulting in the face (and even the body structure) not being correctly rendered. 

For instance, the last target pose was that of a male subject, which had a drastic impact on performance.

Ideally, you should use the target pose of the same subject to get an optimal result. In the demo, we have chosen to ignore this for simplicity to make the model more accessible in in-the-wild scenarios where the target pose may be difficult to obtain.
