### ISSUE TITLE
In the wild Images

### ISSUE THREAD

**Issue by vishnumh** [ankanbhunia/PIDM#7]
Hi Authors,

Thanks for sharing the colab demo. I was trying out the model with some random images from internet and I got this results. Could you comment on any reasons the results deviate for in the wild images ?  (source : https://in.pinterest.com/pin/698198748500499916/)
![results](https://user-images.githubusercontent.com/95316115/219974964-86716d48-ef3e-4149-9096-5c15e034273d.png)

**Comment by ankanbhunia** [comment]
The model performs poorly when the source image contains a complex or dark background. Also, I observed that in extreme in-the-wild cases, sometimes the model can't retain the identity of the person in the source image. But the problem in your example is because of the background. Try using images with a simple, light background.
